apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: gcr.io/YOUR_PROJECT_ID/backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              value: "mongodb+srv://admin:F2EtcD!m9Q77dK-@mycluster01.fbutj.mongodb.net/crio-app?retryWrites=true&w=majority"
            - name: JWT_SECRET
              value: "admin123"
            - name: PORT
              value: "5000"
